name: Python CI

on:
  push:
    branches:
      - main
      - release/*

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies (if needed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      # Run pylint on all Python files in the repo
      - name: Lint with pylint
        run: |
          pylint $(git ls-files '*.py')

      # Run unit tests in the root directory
      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "test_*.py" -v
